package taytom258;

import java.util.Collection;
import java.util.TreeMap;

public class JavaScript {
	
	private static String[] concat(String[] sc, String[] alphabet) {
		  int aLen = sc.length;
		  int bLen = alphabet.length;
		  String[] C = new String[aLen+bLen];
		  System.arraycopy(sc, 0, C, 0, aLen);
		  System.arraycopy(alphabet, 0, C, aLen, bLen);
		  return C;
	}

	public static TreeMap<String, String> parseTSO(String text){

			TreeMap<String, String> tso = new TreeMap<String, String>();

			 //replace strings
			 String LBC = " ";					//Line Break Character

			 //Useful Static Search Strings
			 final String[] ALPHABET = {"A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"};
			 final String SUBJ = " SUBJ: ";
			 final String REF = " REF: ";
			 final String DTG = " DTG ";
			 final int DTGLENGTH = 14;
			 final String PURPOSE = " 1. PURPOSE ";
			 final String GENINFO = " 2. GENERAL CIRCUIT/TRUNK INFORMATION ";
			 final String FACINFO = " 3. FACILITY AND EQUIPMENT INFORMATION ";
			 final String NUMCONT = " 4. NUMBER CONTROL ";
			 final String OTHERSD = " 5. OTHER SPECIFIC DIRECTIONS ";

			 //text sanitization:
			 text = text.replaceAll("\r|\n", LBC);		//remove line breaks and replace with LBC (see //replace strings)
			 text = text.replaceAll("\\s+", LBC);			//remove double spaces and replace with a single space
			 text = text.replace("'", "");		//escape apostrophes
			 text = text.replace("\"", "");		//escape quotes
			 

			 //get basics from the start
			 tso.put("Subject", text.substring(text.indexOf(SUBJ) + SUBJ.length(), text.indexOf(REF)));
			 tso.put("DTG", text.substring(text.indexOf(DTG) + DTG.length(), DTGLENGTH));

			 //Look for evidence that a completion report is NOT required
			 String[] crsp = {
			  "COMPLETION REPORT NOT REQUIRED",
			  "COMPLETION REPORT IS NOT REQUIRED"
			 };
			 boolean crr = true;
			 for (int i=0; i<crsp.length; i++) {
			  if (text.toUpperCase().indexOf(crsp[i]) > -1){
				  crr = false;
			  	}
			 }
			 tso.put("Completion Report Required", String.valueOf(crr));

			 //separate into the primary five sections
			 String[] sections = {};
			 sections[sections.length] = ' ' + text.substring(text.indexOf(PURPOSE) + PURPOSE.length(), text.indexOf(GENINFO));	//section 1
			 sections[sections.length] = ' ' + text.substring(text.indexOf(GENINFO) + GENINFO.length(), text.indexOf(FACINFO));	//section 2
			 sections[sections.length] = ' ' + text.substring(text.indexOf(FACINFO) + FACINFO.length(), text.indexOf(NUMCONT));	//section 3
			 sections[sections.length] = ' ' + text.substring(text.indexOf(NUMCONT) + NUMCONT.length(), text.indexOf(OTHERSD));	//section 4
			 sections[sections.length] = ' ' + text.substring(text.indexOf(OTHERSD) + OTHERSD.length(), text.length() - 4);		//section 5

			 //format section one into a single statement (without the A, B, 1, 2 outline crap)
			 boolean found = true;	//boolean for if the object was found
			 String[] sc = {"1", "2", "3", "4", "5", "6", "7", "8", "9"};
			 concat(sc, ALPHABET);
			 int sci = 0;		//search character index
			 int so = 9;		//start search over at 9 (which will be "A") after numbers fail
			 String ss = "";		//search string
			 while (found) {
			  ss = " " + sc[sci] + ". ";
			  found = false;
			  while (sections[0].indexOf(ss) > -1) {found = true; sections[0] = sections[0].replaceAll(ss, " ");}
			  if (found) {sci++;}
			  if (!found && sci < so) {found = true; sci = so;}
			 }
			 while (sections[0].substring(0, 1).equals(" ")) {sections[0] = sections[0].substring(1, sections[0].length());}
			 tso.put("Purpose", sections[0].replaceAll("\\s+", " "));

			 //save a spot for these:
			 tso.put("Requesting Department", "");
			 tso.put("Circuit Use", "");
			 tso.put("Type of Service", "");

			 //extract important data from section two (sections[1])
			 //the "skippy" entries are for lettered sections that are unimportant or I just didn"t know what they were
			 String skippy = "";
			 String[] items = {
			  "Full CCSD",
			  "TSP",
			  "TSO Action",
			  "Expected In Effect Date",
			  "POC Information",
			  "Quality Control Code",
			  "Traffic Flow",
			  "CCO or CMO",
			  "Data Rate",
			  "Security",
			  "Term",
			  "Signaling",
			  skippy,
			  "TSR Number",
			  "Alternate CCSD"
			};
			 String st = sections[1];
			 for (int i=0; i<items.length; i++) {
			  if (items[i] != skippy) {
			   String as = " " + ALPHABET[i] + ". ";
			   String bs = " " + ALPHABET[i + 1] + ". ";
			   tso.put(items[i], st.substring(st.indexOf(as) + as.length(), st.indexOf(bs)));
			  }
			 }

			 TreeMap<String, String> DEPT_CODES = new TreeMap<String, String>();
			 DEPT_CODES.put("A", "DOS: Department of State");
			 DEPT_CODES.put("B", "NAVY: Department of the Navy");
			 DEPT_CODES.put("C", "JCS: National Command Authorities (JCS)");
			 DEPT_CODES.put("D", "DISA: Defense Information Systems Agency");
			 DEPT_CODES.put("E", "JTF: Joint Tactical Force Headquarters");
			 DEPT_CODES.put("F", "NCS: NCS - minor operating agencies; e.g., Department of Energy, United States Information Agency, Department of Commerce, Department of Interior");
			 DEPT_CODES.put("G", "GSA: General Services Administration (GSA)");
			 DEPT_CODES.put("H", "DOS: Diplomatic Telecommunications System");
			 DEPT_CODES.put("I", "FORGN: Allied Governments - For Circuits required by allied governments and provided over some DCS facilities");
			 DEPT_CODES.put("J", "AIR FORCE: Department of the Air Force");
			 DEPT_CODES.put("K", "TRI: Technical Research Institute");
			 DEPT_CODES.put("L", "FAA: Federal Aviation Administration");
			 DEPT_CODES.put("M", "NASA: National Aeronautics and Space Administration");
			 DEPT_CODES.put("N", "DOD: DOD Agencies not listed; e.g., DIA, NSA, DLA, DNA");
			 DEPT_CODES.put("O", "FORGN: Host country - for all circuits required by any country which is host to the United States.");
			 DEPT_CODES.put("P", "NCS: Other U.S. departments, agencies, commissions, or commercial companies not listed; e.g., Department of Justice, requirement by a commercial company.");
			 DEPT_CODES.put("Q", "FEMA: Federal Emergency Management Agency (FEMA)");
			 DEPT_CODES.put("R", "CINCs: Commanders in Chief (CINCs) Command and Control Circuits");
			 DEPT_CODES.put("S", "OSD: Office of the Secretary of Defense");
			 DEPT_CODES.put("T", "FORGN: Treaty organizations; e.g., NATO");
			 DEPT_CODES.put("U", "ARMY: Department of the Army");
			 DEPT_CODES.put("W", "WHCA: White House Communications Agency");
			 DEPT_CODES.put("X", "DOC: Department of Commerce");
			 DEPT_CODES.put("Y", "JUWTF: Joint Unconventional Warfare Tactical Forces Headquarters");
			 DEPT_CODES.put("Z", "MARCOR: Marine Corps");
			 DEPT_CODES.put("1", "SFOB: Special Forces Operations Base");
			 DEPT_CODES.put("2", "AFSOB: Air Force Special Operations Base");
			 DEPT_CODES.put("3", "NSWTG: Navy Special Warfare Task Group");
			 DEPT_CODES.put("4", "COSCOMFSSG: Tactical Support Command, ie, FSSG Component Combat Service Support Element, Force Service Support Group.");
			 DEPT_CODES.put("5", "TCA: Teltran Communications Analysis");
			 
			 //break the full CCSD down
			 //info from DISAC 310-65-1
			 TreeMap<String, String> USE_CODE = new TreeMap<String, String>();
			 USE_CODE.put("01", "PAT-OP : SPT DSN PRECEDENCE ACCESS THRESHOLDER (PAT) OP. SUPPORT USER ACCESS");
			 USE_CODE.put("02", "PAT-C2 : DSN PRECEDENCE ACCESS THRESHOLDER (PAT) C2 USER ACCESS");
			 USE_CODE.put("A2", "AMACTY : ADMINISTRATIVE ACTIVITIES-MISC");
			 USE_CODE.put("A3", "AIM : AQUISTION INFORMATION MANAGEMENT");
			 USE_CODE.put("A4", "TACCS : TACTICAL ARMY COMBAT SERVICE SUPPORT COMPUTER SYSTEM");
			 USE_CODE.put("A5", "ACIRS : ARMY CRIMINAL INVESTIGATION REPORTING SYSTEM");
			 USE_CODE.put("A7", "AIN : ARMY INTEROPERABILITY NETWORK");
			 USE_CODE.put("AA", "ANRNET : ALASKAN NORAD REGION NETWORK");
			 USE_CODE.put("AB", "COMUSE : IN COUNTRY COMMON USE V/TTY NETWORK");
			 USE_CODE.put("AC", "AACCC : ALASKAN AIR COMMAND AND CONTROL");
			 USE_CODE.put("AD", "DOE-RDO : DEPARTMENT OF ENERGY RADIO NETWORK");
			 USE_CODE.put("AE", "DOESC : DEPARTMENT OF ENERGY SUPPORT CIRCUITS");
			 USE_CODE.put("AF", "HHS : ASFH HHS ASSISTANT SECRETARY FOR HEALTH");
			 USE_CODE.put("AG", "ATFAD : AIR TRAFFIC & AIR FACILITIES ADMINISTRATION");
			 USE_CODE.put("AH", "DOE : DEPARTMENT OF ENERGY");
			 USE_CODE.put("AI", "AFC2N : AIR FORCE COMMAND AND CONTROL NETWORK (AFC2N)");
			 USE_CODE.put("AJ", "DTRA : DEFENSE THREAT REDUCTION AGENCY");
			 USE_CODE.put("AK", "AFRCC : AIR FORCE REMOTE COMPUTER CIRCUITS");
			 USE_CODE.put("AL", "ADNET : ANTI-DRUG NETWORK ATM");
			 USE_CODE.put("AM", "ACIRCUITS IN SUPPORT OF AUTOMATIC MESSAGE PROCESSING SYSTEMS");
			 USE_CODE.put("AN", "NASA ADMINISTRATIVE CIRCUITS");
			 USE_CODE.put("AP", "NAOC VOICE NETWORK");
			 USE_CODE.put("AR", "AMERICAN RED CROSS");
			 USE_CODE.put("AS", "ADMINISTRATIVE SUPPORT-RECRUITING");
			 USE_CODE.put("AT", "TRANSPORTATION COORDINATION NETWORK");
			 USE_CODE.put("AU", "AUTOMATIC SYSTEM FOR TRANSPORTATION DATA (AUTOSTRAD)");
			 USE_CODE.put("AV", "TRANSPORTATION COORDINATOR AUTO COMMAND AND CONTROL INFO SYS");
			 USE_CODE.put("AW", "ATM USER ACCESS");
			 USE_CODE.put("AZ", "DEFENSE STANDARD AMMUNITION COMPUTER SYSTEM");
			 USE_CODE.put("B1", "TRACK SUPERVISION NET");
			 USE_CODE.put("B2", "INTERFACE COORDINATION NET");
			 USE_CODE.put("B3", "DATA COORDINATION NET");
			 USE_CODE.put("B4", "VOICE PRODUCT NET");
			 USE_CODE.put("BB", "AFCC COMMAND NETWORK");
			 USE_CODE.put("BC", "CRIMINAL INVESTIGATION COMMAND MNGEMNT INFO SYS (CIDOMIS)");
			 USE_CODE.put("BD", "FLEET BROADCAST");
			 USE_CODE.put("BE", "SUBMARINE COMMUNICATIONS");
			 USE_CODE.put("BN", "JOINT BROADCAST SYSTEM (JBS) NATO - COMMAND AND CONTROL AUGMENTATION");
			 USE_CODE.put("BS", "JOINT BROADCAST SYSTEM (JBS) - COMMAND AND CONTROL AUGMENTATION");
			 USE_CODE.put("C1", "CLAIMS NETWORK");
			 USE_CODE.put("C2", "EUROPEAN COMMISSARY REGION-82");
			 USE_CODE.put("C3", "COMMUNICATIONS/ELECTRONICS ACTIVITIES-MISC");
			 USE_CODE.put("C4", "COMPTROLLER ACTIVITIES-MISC");
			 USE_CODE.put("C5", "CONTRACTOR SUPPORT SERVICES-MISC");
			 USE_CODE.put("C6", "COMPUTER ASSISTED FORCE MANAGEMENT SYSTEM");
			 USE_CODE.put("C7", "CA CON APPROVAL REQS (PSEUDO CCSDS ASSOC WITH EQUIP-ONLY TSRS)");
			 USE_CODE.put("C8", "USAREUR COMMUNITY AUTOMATION SYSTEM SUPPORT");
			 USE_CODE.put("C9", "ARMY COMSEC COMMODITY LOGISTICS ACCOUNTING INFO MANAGEMENT SYS");
			 USE_CODE.put("CA", "JOINT SURVEILLANCE SYSTEM");
			 USE_CODE.put("CB", "DEFENSE SIMULATION AND INTEGRATION NETWORK");
			 USE_CODE.put("CC", "CRIMINAL INVESTIGATION COMMAND MANAGEMENT INFORMATION SYSTEM");
			 USE_CODE.put("CD", "NATIONAL WARNING SYSTEM");
			 USE_CODE.put("CE", "DEPARTMENT OF TREASURY");
			 USE_CODE.put("CF", "PACFLT COMMAND AND CONTROL");
			 USE_CODE.put("CG", "DSI BACKBONE TRUNK/CIRCUIT");
			 USE_CODE.put("CH", "DSI ACCESS CIRCUIT");
			 USE_CODE.put("CI", "DEPARTMENT OF TREASURY - CUSTOMS (TECS)");
			 USE_CODE.put("CJ", "COMMERCIAL SATELLITE COMMUNICATIONS INITIATIVE");
			 USE_CODE.put("CL", "CONTROL LINE");
			 USE_CODE.put("CM", "COMMUNICATIONS MANAGEMENT OFFICES REPORTING NETWORK");
			 USE_CODE.put("CN", "DEF ADV RESEARCH PROJ AGCY RESOURCES SHARING COMPUTER NETWORK");
			 USE_CODE.put("CO", "CHIEF OF NAVAL OPERATIONS FLASH NETWORK");
			 USE_CODE.put("CS", "SPACE COMMAND DIGITAL INTEGRATED NETWORK");
			 USE_CODE.put("CT", "CONTINGENCIES");
			 
//
//			  'CV':'DECAFTS DEFENSE COMMISSARY AGENCY - FTS2000 TO 2001 TRANSITION',
//			  'CW':'DEPTOFCOMM DEPARTMENT OF COMMERCE',
//			  'CY':'CINCEUR CINCEUR COMMAND AND CONTROL NETWORK',
//			  'CZ':'DFCU DEFENSE FEDERAL CREDIT UNIONS',
//			  'D4':'DEFCONAUAG DEFENSE CONTRACT AUDIT AGENCY',
//			  'D5':'DPACTY DATA PROCESSING/SOFTWARE DEVELOPMENT #NAME?',
//			  'D6':'RESERVED RESERVED FOR FUTURE USE BY THE ARMY',
//			  'D9':'SIDIALISVC SIPRNET DIAL-IN-SERVICE - COMMSERVER',
//			  'DA':'DISA DEFENSE INFORMATION SYSTEMS AGENCY CIRCUITS',
//			  'DB':'THRDAFOP THIRD AF OPERATIONAL NETWORK',
//			  'DC':'DINCORD AUTODIN COORDINATION CIRCUITS (VALIDATED BY HQ, DISA)',
//			  'DD':'DOCCN DISA OPERATIONS CONTROL COMPLEX NETWORK',
//			  'DE':'17 AFOP 17TH AF OPERATIONAL NETWORK',
//			  'DF':'NAV D/F NAVY DIRECTION FINDING NETWORK',
//			  'DG':'DTIC DEFENSE TECHNICAL INFORMATION CENTER ACCESS',
//			  'DH':'DEERS DEFENSE ENROLLMENT/ELIGIBILITY REPORTING SYSTEM',
//			  'DI':'DIA DEFENSE INTELLIGENCE AGENCY COMMUNICATIONS',
//			  'DJ':'NMCC NATIONAL MILITARY COMMAND AND CONTROL SUPPORT',
//			  'DK':'IEMATS IMPROVED EMERGENCY MESSAGE AUTOMATIC TRANSMISSION SYSTEM-PHASE',
//			  'DL':'DSCS DEFENSE SATELLITE COMMUNICATIONS SYSTEM',
//			  'DM':'EMATS EMERGENCY MESSAGE AUTOMATIC TRANSMISSION SYSTEM (JCS)',
//			  'DN':'CRITICOM CRITICAL INTELLIGENCE COMMUNICATIONS',
//			  'DO':'OSD OFFICE OF THE SECRETARY OF DEFENSE',
//			  'DP':'NSAOPRSUP NSA OPERATIONAL SUPPORT',
//			  'DQ':'WEAPCON USAFE AIR WEAPONS CONTROL NETWORK (412L)',
//			  'DR':'DDSCI DOD DEPENDENT SCHOOL COMPUTER INTERCONNECT',
//			  'DS':'DIPLOMATIC DIPLOMATIC TELECOMMUNICATIONS SERVICE',
//			  'DT':'MINUTE PENTAGON MINUTEMAN NETWORK',
//			  'DU':'ATOC ALLIED TACTICAL OPERATIONS CENTER COMMAND & CONTROL NETWORK',
//			  'DV':'USAFE CRCC USAFE COMPUTER-REMOTE/COMPUTER-COMPUTER',
//			  'DW':'USAFE CC USAFE HQ COMMAND AND CONTROL',
//			  'DX':'DSSCOACCT1 DSS CONUS ACCESS T-1',
//			  'DY':'USAFE OSV USAFE OPERATIONS SUPPORT VOICE',
//			  'DZ':'NIDIALISVC NIPRNET DIAL-IN-SERVICE - COMMSERVER',
//			  'E1':'RESERVED RESERVED FOR FUTURE USE BY THE ARMY',
//			  'E2':'TNGMISC TRAINING-MISCELLANEOUS',
//			  'E3':'FEACTY FACILITIES ENGINEERING ACTIVITIES-MISC',
//			  'E4':'ENGCOMS US ARMY ENGINEERING COMMUNICATIONS',
//			  'E5':'EFRRS ENHANCED FREQUENCY RESOURCE RECORDS SYSTEM',
//			  'E7':'CEAP CORPS OF ENGINEERS AUTOMATED PROCESSING (CEAP) NETWORK E8 D EISNET ENGINEER INFORMATION COMMUNICATIONS SYSTEMS',
//			  'E8':'EISNET ENGINEER INFORMATION COMMUNICATIONS SYSTEMS',
//			  'EA':'AIA AIR INTELLIGENCE AGENCY',
//			  'EB':'EBS EMERGENCY BROADCAST SYSTEM',
//			  'EK':'EKMS ELECTRONIC KEY MANAGEMENT SYSTEM',
//			  'EM':'EMSS ENHANCED MOBILE SATELLITE SYSTEM (EMSS)',
//			  'ET':'NTSS NESS, TIROS-N SATELLITE SYSTEM',
//			  'EU':'EUCOM-EMC EUCOM CONTINGENCY CIRCUITS',
//			  'EV':'ETS EUROPEAN TELEPHONE SYSTEM CIRCUITS',
//			  'EW':'ETSTRK EUROPEAN TELEPHONE SYSTEM TRUNK CONVERSION',
//			  'EX':'EUR EXER EXERCISE CIRCUITS (USED FOR TEMPORARY CIRCUITS ONLY)',
//			  'EY':'EXCOMS EXECUTIVE SECURE MOBILE COMMUNICATIONS SYSTEM',
//			  'F1':'ICATM INTERCENTER AIR TRAFFIC MOVEMENT AND CONTROL - OVERSEAS F2 L ATMCR AIR TRAFFIC MOVEMENT AND CONTROL INTERCENTER RADAR HANDOFF',
//			  'F3':'ATMCI AIR TRAFFIC MOVEMENT AND CONTROL INTRA-AREA NONRADAR',
//			  'F4':'ATMCH AIR TRAFFIC MOVEMENT AND CONTROL INTRA-AREA RADAR HANDOFF',
//			  'F5':'ATMCT AIR TRAFFIC MOVEMENT AND CONTROL TOWER TO TOWER',
//			  'F6':'PFBFC PREFLIGHT BRIEFING FILE AND CLOSE (FLIGHT ASSISTANCE)',
//			  'F7':'ATMCN AIR TRAFFIC MOVEMENT AND CONTROL INTERCENTER NONRADAR',
//			  'F8':'EMFMI EXCHANGE OF MILITARY FLIGHT MOVEMENT INFORMATION',
//			  'F9':'SVFIP SERVICE F AIR TRAFFIC MOVEMENT AND CONTROL - INTERPHONE',
//			  'FA':'LOG VOICE AFLC VOICE TIELINE NETWORK',
//			  'FB':'FORENBCST FOREIGN BROADCAST INFORMATION',
//			  'FC':'FBI FEDERAL BUREAU OF INVESTIGATION',
//			  'FE':'LOGAIRNET AFLC AIR LOGISTICS NETWORK',
//			  'FI':'JUSTICDEPT DEPARTMENT OF JUSTICE, ADMIN CIRCUITS',
//			  'FJ':'JUSTTCMS U.S. DEPARTMENT OF JUSTICE TELECOMMUNICATIONS SYSTEM (JUST)',
//			  'FK':'DEA U.S. DEPARTMENT OF JUSTICE DRUG ENFORCEMENT ADMINISTRATION',
//			  'FO':'FLEET OPS FLEET OPERATIONS CONTROL NETWORK',
//			  'FP':'GSA FTS FTS CIRCUITS OF THE GSA',
//			  'FZ':'FESS FACILITY ENGINEERS SUPPLY SYSTEM',
//			  'G1':'TTTEO TOWER-TO-TOWER EXTERNAL OVERRIDE CIRCUIT',
//			  'G2':'WMSCH WEATHER MESSAGE SYSTEM CENTER HIGH-SPEED DATA CIRCUITS',
//			  'G3':'SVACF SERVICE A CENTER TO FSS COLLECT AND DISSEMINATE WEATHER',
//			  'G4':'SVAWW SERVICE A FROM WMSC TO NON-GOVERNMENTAL WEATHER SERVICE',
//			  'G5':'SVAWM SERVICE A FROM WMSC TO MILITARY STATION OF WEATHER INFO',
//			  'G6':'SVAWB SERVICE A FROM WMSC TO WEATHER BUREAU OFFICE G7 L SVCNW SERVICE C COLLECT & DISSEMINATE NONAVIATION WEATHER INFO',
//			  'G8':'SVOFW SVC O COLLECT & DISSEMINATE INTRNTL FLIGHT WEATHER-DOMESTIC',
//			  'G9':'RCAGE RCAG EMERGENCY COMMUNICATIONS (BUEC)',
//			  'GB':'TFFOE TABS FAST FILE AND OPEN-ENDED SERVICE',
//			  'GC':'FAA SVC A FAA SERVICE A',
//			  'GD':'SVBMC SERVICE B MISCELLANEOUS CIRCUITS',
//			  'GF':'CFCBA CENTRAL FLOW CONTROL BETWEEN ATC FACILITIES (COMMAND/CONTROL)',
//			  'GG':'FAA SVC O FAA SERVICE O',
//			  'GJ':'FAA FAA REMOTE-CONTROLLED AIR GROUND',
//			  'GK':'NWSIB NATIONAL WEATHER SERVICE INFLIGHT BRIEFING - SERVICE F',
//			  'GL':'FAA C/C FAA COMMAND AND CONTROL',
//			  'GM':'WTCMS WMCS TELETYPE CIRCUITS (MISCELLANEOUS)',
//			  'GP':'GENFINACC GENERAL FINANCE ACCOUNTING',
//			  'GS':'TURKGENSTF TURKISH NATIONAL CIRCUITS',
//			  'GU':'USCG U.S. COAST GUARD',
//			  'GV':'GCCSBB GLOBAL COMMAND AND CONTROL SYSTEM (GCCS) BACKBONE',
//			  'GW':'GCCSAL GLOBAL COMMAND AND CONTROL SYSTEM (GCCS) ACCESS LINE',
//			  'H1':'DFR DIRECTION FINDER REMOTING',
//			  'H2':'AFTNA AERONAUTICAL FIXED TELECOM NETWORK (AFTN)',
//			  'H3':'SVBFP FLIGHT PLAN TRANSMISSION (HIGH-SPEED) SERVICE B',
//			  'H4':'LOSPO FLIGHT PLAN TRANSMISSION (LOW-SPEED) OVERLOAD AREA & SUPP.',
//			  'H5':'SVBFD FLIGHT PLAN & MILITARY PLANNING FLIGHT INFO SERVICE B',
//			  'H6':'ATMCC ATM&C CENTER-TO-CENTER COMPUTER DATA',
//			  'H7':'ADACT AIRCRAFT DEPARTURE & ARRIVAL INFO CENTER TO TOWER',
//			  'H8':'FPICT FLIGHT PLAN INFO COMPUTER FDEP CENTER TO TOWER',
//			  'H9':'SVBIF IFR FLIGHT PLAN ENTRY (CIVILIAN OR MILITARY) SERVICE B',
//			  'HA':'SYS VOICE AFSC VOICE TIELINE NETWORK',
//			  'HB':'SYS PROJ AFSC PROJECT SUPPORT NETWORK',
//			  'HC':'16AFOPR 16 AF OPERATIONAL CIRCUITS',
//			  'HD':'TACCON TACTICAL AIR CONTROL SYSTEM (407L) CIRCUITS',
//			  'HE':'USCENTAFCC USCENTAF COMMAND AND CONTROL COMMUNICATIONS',
//			  'HF':'HFGCS HF GLOBAL COMMUNICATIONS SYSTEM',
//			  'HN':'MEPRS MEDICAL EXPENSE AND PERFORMANCE REPORTING SYSTEM',
//			  'HS':'HRASAHEALT H RESOURCES AND SERVICES ADMINISTRATION',
//			  'HV':'MULSATRAC AFSC MULTIPLE SATELLITE TRACKING NETWORK',
//			  'HW':'FDIO FLIGHT DATA INPUT/OUTPUT',
//			  'I1':'CITACSDNET CLASSIFIED INTERGRATED TACTICAL STRATEGIC DATA NETWORK',
//			  'I2':'UITACSDNET UNCLASSIFIED INTERGRATED TACTICAL STRATEGIC DATA NETWORK',
//			  'IA':'USIA U.S. INFORMATION AGENCY',
//			  'IC':'AAAAS DSN ACCESS LINE (SEE DISAC 310-65-1, CHAPTER 14)',
//			  'ID':'INMARSAT DOD AND NON-DOD INMARSAT DITCO-PROCURED',
//			  'IG':'NOSGD NOS GEODETIC DATA',
//			  'IM':'AIMS AUTOMATED INSTRUCTIONAL MANAGEMENT SYSTEM',
//			  'IN':'IMMNATSVC IMMIGRATION AND NATIONALIZATION SERVICE',
//			  'IP':'DISNACCESS NIPRNET ACCESS LINE',
//			  'IR':'DISNROUTER DISN BACKBONE ROUTER INTER-NODAL CIRCUIT (INC)',
//			  'IT':'IGNET ARMY INSPECTOR GENERAL NETWORK',
//			  'IU':'DTRMBLKINT DISN XMN RESOURCE MUX (BLACK) INTER-NODAL NON-CHANNELIZED CIRCUIT INTER-NODAL (BACKBONE) INFRASTRUCTURE',
//			  'IV':'INOBRDTCKT INTER-NODAL BROADBAND TRANSMISSION MANAGER CIRCUIT',
//			  'IW':'DISN MUX DISN MULTIPLEXER PACKAGE SYSTEM',
//			  'IX':'DISNSTAMUX DISN STAT MULTIPLEXER CONTROL SYSTEM',
//			  'IY':'DISNSOXMTN DISN SONET TRANSMISSION',
//			  'IZ':'DISNPOPINC DISN POP-SPINE ROUTER INTER-NODAL CIRCUIT (INC)',
//			  'J1':'LOTLC LOCAL TELETYPE CIRCUITS',
//			  'J2':'RCAGA RCAG REMOTE COMMUNICATIONS AIR-GROUND PRIMARY CIRCUIT',
//			  'J3':'RCAGF RCAG LASS CIRCUITS',
//			  'J4':'LRRRN LONG-RANGE RADAR REMOTING NARROWBAND CIRCUITS',
//			  'J5':'ASLOB AIRPORT SURVEILLANCE LOCAL ON-BASE RADAR',
//			  'J6':'NWSRF NATIONAL WEATHER SERVICE RADAR FAX',
//			  'J7':'RTMLW RADIO & TV MICROWAVE LINK DATA TRANSMITTED BETWEEN FACILITIES',
//			  'J8':'RCAGB RCAG SS-1 CIRCUIT',
//			  'J9':'RCAGC RCAG REDUNDANT OR DIVERSE ROUTING CIRCUITS',
//			  'JA':'ACC PAS ACC PRIMARY ALERT SYSTEM',
//			  'JC':'SHORT ORD ACC SHORT ORDER NETWORK',
//			  'JD':'ACCOMCON ACC COMMAND AND CONTROL NETWORK (465L)',
//			  'JE':'ACCOMNET ACC TELETYPEWRITER NETWORK',
//			  'JF':'DMSP DEFENSE METEOROLOGICAL SATELLITE PROGRAM (DMSP)',
//			  'JG':'ACCTELNET ACC TELEPHONE NETWORK',
//			  'JH':'JOTS JOINT OPERATIONAL TACTICAL SYSTEM',
//			  'JI':'JWICS JOINT WORLDWIDE INTELLIGENCE COMMUNICATIONS SYSTEM BACKBONE',
//			  'JJ':'ACC ORDER ACC VOICE ORDERWIRE JK A COMUSKORCC COMUSKOREA COMMAND, CONTROL, AND OPERATIONAL NETWORK',
//			  'JL':'POST ATTCC ACC POST ATTACK COMMAND & CONTROL SYSTEM (GROUND ENVIRONMENT)',
//			  'JM':'ACCICBMSC ACC ICBM SUPPORT COMMUNICATIONS',
//			  'JN':'JITFJITCCS JOINT INTERFACE TEST FORCE-JOINT INTEROPERBLY TECH CMD/CTRL SYS',
//			  'JP':'JP COMNET PACIFIC COMMAND JOINT NETWORK',
//			  'JQ':'MPR-JSS MILITARY PAY REDESIGN-JOINT SERVICES SOFTWARE',
//			  'JS':'JOINSTUGRP JOINT STUDIES GROUP',
//			  'JT':'JOSTEPPROG JOINT "STEP" PROGRAM',
//			  'JU':'JTELS JUMPS INQUIRY TELEPROCESSING SYSTEM',
//			  'JX':'COMUSJAPAN COMUSJAPAN COMMAND AND CONTROL COMMUNICATIONS',
//			  'K1':'NHBFS NAVIGATIONAL HOMING BEACON TO FLIGHT SERVICE CENTER',
//			  'K2':'ILAAT ILS LOCAL APPROACH AIDE TO TOWER - LOCAL SERVICE',
//			  'K3':'RTRLA REMOTE TRANSMITTER RECEIVER LOCAL AIRPORT SERVICE',
//			  'K4':'RCOMF REMOTE COMMUNICATIONS OUTLET MULTIPLE FREQUENCY',
//			  'K5':'IFSRT INTERNATIONAL FLIGHT SERVICE RECEIVE-TRANSMIT AIR-GROUND',
//			  'K6':'MRFCK MISCELLANEOUS REMOTE FACILITY CIRCUITS',
//			  'K7':'RRRWM RVR.RRH.RBC. MISCELLANEOUS WEATHER MEASURING EQUIPMENT (LOCAL)',
//			  'K8':'EFASV ENROUTE FLIGHT ADVISORY SERVICE (EFAS)',
//			  'K9':'ALSYS AIRPORT LIGHTING SYSTEM (LOCAL)',
//			  'KA':'INTEL INTELLIGENCE',
//			  'KB':'KWAN KOREAN WIDEBAND AREA NETWORK (KWAN)',
//			  'KC':'KBSC KPREAN BATTLE SIMULATION CENTER (KBSC)',
//			  'KE':'NMFSSWTS NMFS SOUTHWEST TELECOMMUNICATIONS SYSTEM',
//			  'KG':'CIRC-II-VM CENTRAL INFORMATION REFERENCE AND CONTROL SYSTEM',
//			  'KK':'CC COMMAND AND CONTROL MISC',
//			  'KL':'KEYLINE KEYING LINES',
//			  'KM':'CFROK COMBINED FORCES REPUBLIC OF KOREA COMMAND AND CONTROL (CFROK)',
//			  'KN':'NAOC TTY NAOC TELETYPEWRITER NETWORK',
//			  'KR':'ANMCC ANMCC SUPPORT',
//			  'KS':'REL COPAN RELOCATION COPAN',
//			  'KT':'ANMCC1ALT ANMCC SUPPORT (FIRST ALTERNATE)',
//			  'KU':'ALTAN USAF RELOCATION VOICE NETWORK',
//			  'KW':'MEECN NCA/JCS MINIMUM ESSENTIAL EMERGENCY COMMUNICATIONS NETWORK',
//			  'KZ':'NMCS DATA NMCS DATA TRANSMISSION',
//			  'L1':'REIMN REIMBURSABLE NAFEC',
//			  'L2':'REIMR REIMBURSABLE R&D',
//			  'L3':'REIMA REIMBURSABLE ALASKA ADMINISTRATION',
//			  'L4':'REIMM REIMBURSABLE MANAGEMENT SYSTEM',
//			  'L6':'STAFC STAFF COMMUNICATIONS COMMAND AND CONTROL (STAFC)',
//			  'L7':'TTC TELEWRITER, TALOS CIRCUITS',
//			  'L8':'ATSWS ALASKA TELEPHONE SWITCHING CENTER',
//			  'LB':'LGACTY LEGAL ACTIVITIES - MISC',
//			  'LC':'AL PUBLIC PUBLIC-OFFERING TELEPHONE/TELEGRAPH NETWORK',
//			  'LE':'ULENET/PAL USAREUR LIBRARY EDUCATION NTWK AND PATRON ORIENTED LIBRARY SYS',
//			  'LH':'USATACCOM USATACCOM U.S. ARMY ALASKA TACTICAL COMMUNICATIONS',
//			  'LP':'DLAT DSN LOOP-AROUND TRUNKS',
//			  'LR':'LIVE OAK LIVE OAK CIRCUITS BETWEEN NON-U.S. COMPONENTS',
//			  'LS':'JCALS JOINT COMPUTER-AIDED ACQUISTION AND LOGISTIC SUPPORT',
//			  'LT':'LSACTY LOGISTICS/SUPPLY ACTIVITIES-MISC',
//			  'LW':'LWDMUXPKGS LIGHTWAVE DIVISION MULTIPLEX PACKAGE SYSTEM',
//			  'MA':'EAS MSL EASTERN MISSILE RANGE MISSILE SPACE NETWORK',
//			  'MB':'MPACTY MANPOWER/PERSONNEL ACTIVITIES-MISC',
//			  'MC':'MARINES U.S. MARINE CORPS',
//			  'MD':'MOBILIZE MOBILIZATION',
//			  'MF':'MEDACT MEDICAL ACTIVITY (MEDACT)',
//			  'MH':'TRACTY TRANSPORTATION ACTIVITIES-MISC',
//			  'MI':'MIS MANAGEMENT INFORMATION SYSTEMS (MIS)',
//			  'ML':'E-MAIL COMMON USER ELECTRONIC MAIL SERVICE',
//			  'MN':'MAN METROPOLITAN AREA NETWORK',
//			  'MP':'AMPMN ARMY MATERIAL PLAN-MODERNIZATION NETWORK',
//			  'MR':'WES MSL WESTERN MISSILE/SPACE SUPPORT NETWORK',
//			  'MU':'ATECM ARMY TEST & EVALUATION MANAGEMENT NETWORK',
//			  'MV':'MIL ASSIST U.S. MILITARY ASSISTANCE NETWORK',
//			  'MW':'MWACTY MORALE, WELFARE AND RECREATION ACTIVITIES-MISC',
//			  'MZ':'NIMA NATIONAL IMAGERY AND MAPPING AGENCY COMMUNICATIONS',
//			  'N1':'NSTAR NORTHSTAR NETWORK (NAOC, LOOKING GLASS, AF-1)',
//			  'N2':'COMSACNIPR COMMSERVER ACCESS - NIPRNET',
//			  'NA':'REDCC USREDCOM COMMAND AND CONTROL CIRCUITS',
//			  'NB':'CENTCOM USCENTCOM COMMAND AND CONTROL CIRCUITS',
//			  'NC':'NMC-NOC NETWORK MANAGEMENT CIRCUITS (NETWORK OPERATION CENTERS)',
//			  'NF':'WAWAS WASHINGTON AREA WARNING SYSTEM',
//			  'NG':'NATLGRDTRA NATIONAL GUARD - TRAINING',
//			  'NH':'EDNET DOD SATELLITE EDUCATION NETWORK',
//			  'NJ':'NGNET NATIONAL GUARD NETWORK',
//			  'NK':'INFODIS INFORMATION DISSEMINATION',
//			  'NM':'NMCINATRK NMCI NETWORK ACCESS TRUNK',
//			  'NN':'FNAVS FEMA NATIONAL VOICE SYSTEM',
//			  'NP':'FEMA FEDERAL EMERGENCY MANAGEMENT AGENCY SUPPORT',
//			  'NS':'SPECREQMTS NAVY SECURITY GROUP',
//			  'NT':'FNATS FEMA NATIONAL TELETYPE SYSTEM',
//			  'OC':'NAVCONORD NAVAL COMMUNICATIONS MASTER CONTROL STATION COMMAND/CORD',
//			  'OJ':'NASCOMODSN NASCOM OPERATIONAL DSN',
//			  'OL':'LINK OW LINK ORDERWIRE',
//			  'OM':'TELMETROW TELEMETRY ORDERWIRE',
//			  'ON':'NON-GIG OW NON-GIG ORDERWIRE',
//			  'OO':'SYSOW SYSTEM ORDERWIRE',
//			  'OR':'TTYOW TELETYPE ORDERWIRE',
//			  'OU':'ORACTY ORDINANCE ACTIVITIES-MISC',
//			  'OX':'EXPRSOW EXPRESS ORDERWIRE',
//			  'PA':'COPAN AF COMMAND POST VOICE NETWORK',
//			  'PB':'ALT CMD AF ALTERNATE COMMAND NETWORK',
//			  'PC':'AIR CMD AF COMMAND NETWORK',
//			  'PD':'PDIP PROGRAMMABLE INDICATOR DATA PROCESSOR CIRCUITS',
//			  'PE':'FDED AF FLIGHT DATA ENTRY PRINT-OUT NETWORK',
//			  'PF':'PAACTY PUBLIC AFFAIRS ACTIVITIES-MISC',
//			  'PG':'AFPROMGT AF PROJECT MANAGEMENT NETWORK',
//			  'PH':'PAC NET ARMY, AIR FORCE, NAVY NETWORK',
//			  'PI':'PMIDNX PANAMA IDNX NETWORK',
//			  'PJ':'PERDMS PERSONNEL DEPLOYMENT AND DISTRIBUTION MGMT NETWORK',
//			  'PK':'PANMW PANAMA MICROWAVE SYSTEM',
//			  'PL':'PIMS PARTNERSHIP FOR PEACE INFORMATION MANAGEMENT SYSTEM (PIMS)',
//			  'PM':'PASTRAM PASSENGER TRAFFIC MANAGEMENT SYSTEM',
//			  'PP':'ARCOOP ARMY CONTINUITY OF OPERATIONS NETWORK',
//			  'PQ':'APAM ACQUISITION/PROCUREMENT ACTIVITIES-MISC',
//			  'PR':'CIVPERNET CIVILIAN PERSONNEL NETWORK',
//			  'PS':'PRESS COMMERCIAL PRESS SERVICES',
//			  'PT':'PETDIST PETROLEUM AND DISTRIBUTION COMMAND NETWORK',
//			  'PV':'PPACTY PLANS AND POLICY ACTIVITIES-MISC',
//			  'PW':'PRACTY PROPERTY DISPOSAL OFFICE/RESALE ACTIVITIES-MISC',
//			  'PX':'AAFES ARMY AND AIR FORCE EXCHANGE SERVICE',
//			  'Q1':'AWDS AUTOMATED WEATHER DISTRIBUTION SYSTEM',
//			  'Q2':'NEXRAD NEXT GENERATION WEATHER RADAR',
//			  'Q3':'HFRB HIGH FREQUENCY REGIONAL BROADCAST',
//			  'QA':'MCCRS MAC COMMAND CONTROL RECORD COMMUNICATIONS SYSTEM',
//			  'QD':'WXACTY WEATHER ACTIVITIES-MISC',
//			  'QE':'WEATTY 1 WEATHER TELETYPEWRITER (CIVIL FAA A, C, O)',
//			  'QG':'WEATTY 2 WEATHER TELETYPEWRITER',
//			  'QI':'WEAFAX 1 WEATHER FAX (CIVIL, U.S. WEATHER BUREAU)',
//			  'QJ':'WEAFAX 2 WEATHER FAX',
//			  'QM':'MACCOMCON MAC COMMAND CONTROL VOICE CIRCUITS',
//			  'QN':'NATO NATO CIRCUITS BETWEEN U.S. COMPONENTS',
//			  'QO':'NATO NATO CIRCUITS BETWEEN NON-U.S. COMPONENTS',
//			  'QR':'NATO NATO CIRCUITS BETWEEN NON-U.S. AND A U.S. COMPONENT',
//			  'QS':'MACOPSPT MAC OPERATIONAL SUPPORT CIRCUITS',
//			  'QU':'TDIST TACTICAL DIGITAL INTERSWITCH TRUNK. (NON GIG)',
//			  'RA':'ARADS ARMY RECRUITING AND ACCESSION DATA SYSTEM',
//			  'RC':'CCRESFORCS C&C OF RESERVE FORCES WITHIN RESERVE COMMAND ORGANIZATION',
//			  'RF':'PAFCONET PACAF COMMAND AND CONTROL NETWORK',
//			  'RH':'R & D RESEARCH AND DEVELOPMENT - MISC',
//			  'RI':'TRI TECHNICAL RESEARCH INSTITUTE',
//			  'RM':'RA/IAS REMOTE ALARM/INTRUSION ALERT SYSTEMS-MISC',
//			  'RN':'FORGN FOREIGN CIRCUITS BETWEEN U.S. COMPONENTS',
//			  'RP':'RAPID RANDOM ACCESS PERSONNEL INFORMATION DATA SYSTEM',
//			  'RQ':'RSNCTRLCKT MONITORING AND CONTROL CKT FOR THE DEFENSE RED SWITCH NETWORK',
//			  'RR':'FORGN FOREIGN CIRCUITS BETWEEN NON-U.S. AND U.S. COMPONENTS',
//			  'RS':'AFRS AFRTS/STARS AND STRIPES',
//			  'RT':'ATRRS ARMY TRAINING REQUIREMENTS AND RESOURCES SYSTEM',
//			  'RU':'MILDEP-RST INTERSWITCH TRUNK BETWEEN MILDEP DRSN SWITCHES',
//			  'RV':'MILDEP-RSA ACCESS CIRCUIT INTO MILDEP DEFENSE RED SWITCH NETWORK (DRSN)',
//			  'RW':'GIG-RST INTERSWITCH TRUNK BETWEEN GIG DRSN SWITCHES',
//			  'RX':'GIG-RSA ACCESS CIRCUIT INTO GIG DEFENSE RED SWITCH NETWORK (DRSN)',
//			  'RY':'DSNISTSVS INTERSWITCH TRUNK BETWEEN GIG DRSN AND DSN SWITCH',
//			  'RZ':'RCAS RESERVE COMPONENT AUTOMATION SYSTEM',
//			  'S1':'ASNET ARMY SUPERCOMPUTER NETWORK',
//			  'S2':'SATMS SECURITY ASSISTANCE TRAINING MANAGEMENT SYSTEM',
//			  'S3':'ISAN INTELLIGENCE AND SECURITY AUTOMATED NETWORK (AMC)',
//			  'S5':'CTASC-II CORPS THEATER ADP SERVICE CENTER NETWORK-SECOND GENERATION',
//			  'S6':'SISOCS STREAMLING INFORMATION SVC OPS CONSOLIDATION STUDY (SISOCS)',
//			  'S7':'SIPRNETAL SIPRNET ACCESS LINE',
//			  'S8':'SIPRNETCC SIPRNET CONTROL CIRCUITS',
//			  'S9':'SUBINFOSVC SUSTAINING BASE INFORMATION SERVICE',
//			  'SA':'SERUSINCRP SERIOUS INCIDENT REPORTING',
//			  'SB':'SPCS TO SA SPECIAL COMMUNICATIONS SUPPORT TO SAUDI ARABIA',
//			  'SC':'SCPNCC SCP NETWORK CONTROL CIRCUIT',
//			  'SD':'ISDN TERMI NAL',
//			  'SE':'SCIENTIFIC AND ENGINEERING (S&E) COMMUNICATIONS SUPPORT',
//			  'SF':'STANDARD ARMY FINANCIAL SYSTEM (STANFINS)',
//			  'SL':'DEFENSE SIMULATIONS INTERNET/SYNTHETIC THEATER OF WAR-EUROPE',
//			  'SM':'STRATEGIC DEFENSE INITIATIVES (SDI) SUPPORT',
//			  'SN':'SHARED LOGIC OFFICE AUTOMATION NETWORK',
//			  'SO':'SPARE CHANNEL',
//			  'SP':'SPARE PATCH/INTERCONNECT',
//			  'SR':'AN/USC-28 RECEIVE "PN" SELECT CONTROL',
//			  'SS':'SPECIAL SECURITY OFFICE NETWORK',
//			  'ST':'SIPRNET BACKBONE',
//			  'SU':'DEFENSE LOGISTICS AGENCY LEASED COMMUNICATIONS SERVICE',
//			  'SV':'SHIP REPAIR/ENGINEERING ACTIVITIES-MISC',
//			  'SW':'COMMSERVER ACCESS - SIPRNET',
//			  'SX':'ARMY SYS WIDE PROJECT FOR ELECTRONIC EOPT AT DEPOTS-EXTENDED',
//			  'SY':'SONET TRANSMISSION SYSTEM',
//			  'SZ':'AIR FORCE SUPPORT DATA NETWORK',
//			  'T1':'GIG STATISTICAL TDM PACKAGE SYSTEM',
//			  'T2':'NON-GIG TDM PKG SYS (FOR USE WITH TYPE SERVICE CODE "M"/"X")',
//			  'T3':'TELTRAN COMMUNICATIONS ANALYSIS',
//			  'T4':'NON-GIG TDM PKG SYSTEM (FOR USE WITH TYPE SERVICE CODE "M"/"X")',
//			  'T5':'NON-GIG STATISTICAL TDM PKG SYS (USE WITH TYPE SVC CODE "M")',
//			  'T6':'TACTICAL DIGITAL INFORMATION LINK',
//			  'T7':'TACTICAL VOICE INFORMATION LINK',
//			  'T8':'CARIBBEAN REGIONAL COMMUNICATIONS NETWORK',
//			  'T9':'DSN SWITCH-TO-SWITCH/SWITCH-TO-DPAS TDM PACKAGE SYSTEM',
//
//			  'TA':'TAC OPERATIONS SUPPORT TTY NETWORK',
//			  'TB':'TAC COMMAND AND CONTROL VOICE ALERTING SYSTEM',
//			  'TC':'TAC OPERATIONS SUPPORT VOICE SYSTEM NETWORK',
//			  'TD':'TAC REMOTE COMPUTER CIRCUITS',
//			  'TE':'TEMP ARMY, AF, NAVY TEMP (SEE DISAC 310-65-1, CHAPTER 14)',
//			  'TF':'DEPARTMENT OF STATE',
//			  'TG':'TAC TACTICAL AIR CONTROL SYSTEM IN-GARRISON TRAINING NETWORK',
//			  'TH':'TRI-CARE HEALTH SYSTEM',
//			  'TJ':'CRITICOM RED TDM PACKAGE SYSTEM',
//			  'TK':'CRITICOM BLACK TDM PACKAGE SYSTEM',
//			  'TL':'US ARMY TRADOC LIBRARY AND INFORMATION NETWORK (TRAILNET)',
//			  'TM':'GIG AN/FCC-100 PKG SYS(DTN ONLY)(CODE TN FOR OTHR FCC-100TRKS)',
//			  'TN':'GIG TIME DIVISION MULTILIEX PACKAGE SYSTEM',
//			  'TO':'TELEMETRY/ORDERWIRE PACKAGE SYSTEM TRUNK',
//			  'TP':'SPEECH PLUS SYSTEM',
//			  'TQ':'FREQUENCY SUBDIVIDED MULTIPLE MODEM SYSTEM (DIGITAL)',
//			  'TR':'TRACKING NETWORK',
//			  'TS':'DSS INTERNODAL TRUNKS',
//			  'TT':'DTC/DSS TRANSITION CUTOVER TRUNKS',
//			  'TU':'U.S. DEPARTMENT OF THE INTERIOR',
//			  'TV':'SYSTEM TIMING',
//			  'TW':'FAST PACKET SWITCHING ACCESS PACKAGE SYSTEM',
//			  'TX':'VFCT SYSTEM',
//			  'TZ':'AFTAC DATA NETWORK',
//			  'U2':'REMOTE DATA LINK BTWN AN EOF HOST SWITCH AND A REMOTE SWITCH',
//			  'U4':'DIAL SERVICE ASSISTANCE (DSA) TRUNK',
//			  'U5':'OPERATOR BUSY VERIFICATION TRUNK',
//			  'U6':'CENTRALIZED COMMERCIAL DIAL ACCESS TRUNK',
//			  'U7':'DSN COMMON CHANNEL SIGNALING DATA LINK',
//			  'U8':'EMERGENCY FACILITIES TRUNK',
//			  'U9':'DSA OPERATOR DEFLECT TRUNK',
//			  'UA':'COMMON USER TELETYPEWRITER SERVICE',
//			  'UB':'COMMON USER VOICE SERVICE',
//			  'UC':'TRUNK CIRCUIT BETWEEN VOICE CONCENTRATOR SYSTEM EQUIPMENT',
//			  'UD':'DRSN INTERSWITCH TRUNK',
//			  'UE':'COMMON USER DIGITAL DATA',
//			  'UF':'COMMON USER FAX (OTHER THAN WEATHER)',
//			  'UH':'WIDEBAND SECURE VOICE DIGITAL TRUNK (FOR USE WITH TYPE SVC M)',
//			  'UI':'USAREUR INSTALLATION COMMUNITY AUTOMATION SYSTEM',
//			  'UJ':'ARMY SIPRNET NETWORK (A-SIPR) (EUROPE USE ONLY)',
//			  'UL':'GIG AUTOMATIC RECORD COMMUNICATIONS NETWORK CIRCUITS',
//			  'UM':'SPECIAL PURPOSE NETWORK',
//			  'UO':'AF AIR OPERATIONS NETWORK',
//			  'UQ':'1ST FROM A DSN MFS TO A TACTICAL GATEWAY SWITCH',
//			  'US':'DSN IST FM END OFC SW (INCL END OFC SLIDE OF MF SW)TO REMOTE SW',
//			  'UT':'DSN ACCESS LINE FM NODE SW/END OFC SW TO NON-DSN (SVC/AGCY) SW',
//			  'UU':'DSN IST CONNECTING NODE SWITCHES',
//			  'UV':'DSN IST CONNECTING END OFC SWITCHES (COMMUNITY OF INTEREST)',
//			  'UW':'INTERDEPARTMENTAL DIAL TELEPHONE NETWORK',
//			  'UX':'DSN IST FM NODE SW TO END OFC SW',
//			  'UY':'DSN DIAL SUBSCRIBER',
//			  'UZ':'TANDEM SW INTERSITE TRUNK CKT (I.E. EPABX - EPABX)',
//			  'VA':'VETERANS ADMINISTRATION',
//			  'VC':'TRUNK CIRCUIT BETWEEN VOICE CONCENTRATOR SYSTEM EQUIPMENT',
//			  'VM':'VERTICAL FORCE DEVELOPMENT MANAGEMENT INFO SYSTEM(VFDMIS)',
//			  'VN':'PUBLIC DATA NETWORK SERVICE',
//			  'VP':'SPECIAL SUPPORT NETWORK (DISA USE ONLY)',
//			  'VQ':'MYSTIC STAR NETWORK',
//			  'VS':'VIDEO TELECONFERENCING SWITCHABLE TO DATA',
//			  'VT':'VIDEO TELECONFERENCING NETWORK',
//			  'VV':'VERY SMALL APERTURE (VSAT) - COMMAND AND CONTROL AUGMENTATION',
//			  'VW':'SATELLITE NETWORK - COMMAND AND CONTROL AUGMENTATION',
//			  'VX':'VIDEO TELECONFERENCING NETWORK',
//			  'WA':'ANTISUBMARINE WARFARE COMMUNICATIONS',
//			  'WF':'WASHFAX HIGH SPEED DIGITAL FACSIMILE',
//			  'WH':'WHEELHOUSE NETWORK',
//			  'WL':'WATER CONTROL, LOCK AND DAM FACILITIES',
//			  'WN':'WIDE AREA NETWORK',
//			  'WT':'WHCA TEMPORARY TRAVEL',
//			  'WX':'NAVY WEATHER',
//			  'WY':'THEATER AUTOMATED COMMAND AND CONTROL INFO MANAGEMENT SYSTEM',
//			  'WZ':'USAREUR TACTICAL COMMAND AND CONTROL SYSTEM',
//			  'XA':'AUTOMATION OF FIELD OPERATION AND SERVICES SYSTEM',
//			  'XC':'NWS COMPUTER PROGRAMING SUPPORT SERVICES',
//			  'XD':'NWS DIGITAL FACSIMILE NETWORK (DIFAX)',
//			  'XF':'NWS FORECAST OFFICE FACSIMILE SYSTEM (FOFAX)',
//			  'XG':'NWS INTERNATIONAL WEATHER COMMUNICATIONS SYSTEM',
//			  'XH':'NWS HYDROLOGIC FORECAST SYSTEM',
//			  'XI':'NWS NOAA FIRE WEATHER SERVICE',
//			  'XJ':'NWS INTRA-ALASKA FAX NETWORK',
//			  'XL':'NWS LOCAL PUBLIC SERVICE COMMUNICATIONS FACILITIES',
//			  'XM':'NWS NATIONAL & AVIATION METEOROLOGICAL FACSIMILE SYSTEM(NAMFAX)',
//			  'XN':'NWS NATIONAL FACSIMILE NETWORK (NAFAX)',
//			  'XP':'NWS RRS (RADAR REMOTE SYSTEM)',
//			  'XQ':'GOES, TELEPHOTO FACSIMILE SYSTEM (GOESFAX)',
//			  'XR':'NWS RADAR REPORTING & WARNING COORDINATION SYSTEM (RAWARC)',
//			  'XS':'NWS HURRICANE AND SEVERE STORM WARNING SYSTEM',
//			  'XU':'NWS SEISMIC AND TSUNAMI TELECOMMUNICATIONS SYSTEM',
//			  'XW':'NOAA WEATHER WIRE SERVICE (NWWS)',
//			  'XY':'RADAR DATA PROCESSOR SYSTEM (RADAP)',
//			  'XZ':'MISCELLANEOUS WEATHER COMMUNICATIONS SYSTEM',
//			  'YA':'FLEET SHIP-SHORE ACCESS',
//			  'YB':'ALASKA COMMAND AND CONTROL',
//			  'YC':'CINCLANT CINCUSJFCOM COMMAND AND CONTROL NETWORK',
//			  'YD':'CINCSOUTH COMMAND AND CONTROL NETWORK',
//			  'YE':'SPACE DEFENSE SYSTEM',
//			  'YF':'DEW LINE/BMEWS SUPPORT NETWORK',
//			  'YI':'NORAD/ADC OVER-THE-HORIZON NETWORK',
//			  'YK':'SAE DSN SWITCHED NETWORK',
//			  'YM':'SEA-LAUNCH BALLISTIC MISSILE (SLBM) DETECTION AND WARNING SYS',
//			  'YN':'NORAD/ADC GROUND COMMUNICATIONS NETWORK',
//			  'YP':'NORAD SURVEILLANCE AND TACTICAL NETWORK',
//			  'YQ':'NORAD ADC POINT-TO-POINT',
//			  'YS':'OCEAN SYSTEMS NETWORK',
//			  'YW':'BCC DATA CONFERENCE CIRCUIT',
//			  'YX':'BCC VOICE CONFERENCE CIRCUIT',
//			  'YY':'AN/USC-28 CONTROL CIRCUIT',
//			  'YZ':'NAVY SPACE SURVEILLANCE NETWORK',
//			  'ZA':'SATELLITE CONTROL/REPORTING COMMUNICATIONS',
//			  'ZB':'TACTICAL COMMAND AND CONTROL',
//			  'ZD':'SEARCH AND RESCUE',
//			  'ZE':'ENTERPRISE FLIGHT ASSISTANCE SERVICE',
//			  'ZF':'WATS FLIGHT ASSISTANCE SERVICE',
//			  'ZG':'MANAGEMENT/COORDINATION NETWORK',
//			  'ZH':'MULTIPLE SUBSCRIBER EQUIPMENT (MSE)',
//			  'ZK':'GROUND FORCES AIR SUPPORT NETWORK',
//			  'ZM':'MILITARY AIR TRAFFIC CONTROL AND FLIGHT FACILITIES NETWORK',
//			  'ZN':'INTELLIGENCE COLLECTION/DISSEMINATION NETWORK',
//			  'ZP':'CANADIAN CIRCUITS',
//			  'ZQ':'LOGISTICS NETWORK',
//			  'ZR':'FLIGHT FOLLOWING/AIR OPS SERVICE NETWORK',
//			  'ZS':'AIR TRAFFIC CONTROL/FLIGHT FACILITIES',
//			  'ZW':'BALLISTIC MISSILE EARLY WARNING SYSTEM'
//			 };
			 TreeMap<String, String> SVC_TYPE = new TreeMap<String, String>();
			 SVC_TYPE.put("A", "Teletype service other than GIG Switched Networks");
			 SVC_TYPE.put("B", "DSN Access Line");
			 SVC_TYPE.put("C", "DSN Interswitch Trunk");
			 SVC_TYPE.put("D", "Data other than GIG Switched Networks");
			 SVC_TYPE.put("E", "Defense Message System Transition Hub (DTH) Access Line");
			 SVC_TYPE.put("F", "Defense Message System Transition Hub Interswitch Trunk");
			 SVC_TYPE.put("G", "Permanent Virtual Circuits");
			 SVC_TYPE.put("H", "SONET/SDH Package System. (No Channel Accounting by DISA.)");
			 SVC_TYPE.put("I", "Non-Red Switch secure voice circuit that does not access DSN. (For non-Red Switch secure voice circuits that access DSN type service code B DSN Access Line will be used.)");
			 SVC_TYPE.put("J", "Facsimile or Telephoto other than GIG Switched Networks");
			 SVC_TYPE.put("K", "Continuous Wave");
			 SVC_TYPE.put("L", "DSSCS DTH Access Line");
			 SVC_TYPE.put("M", "Package System. No channel accounting by DISA");
			 SVC_TYPE.put("N", "DSN Access Line servicing an Red Switch subscriber or switch");
			 SVC_TYPE.put("O", "Switched Virtual Circuits");
			 SVC_TYPE.put("P", "Interswitch trunk/circuit for switched networks other than DISN networks");
			 SVC_TYPE.put("Q", "DTH Interchange Circuits circuits between DTH and other switched networks except DSN");
			 SVC_TYPE.put("R", "Alternate Voice/Record other than GIG Switched Networks");
			 SVC_TYPE.put("S", "Video");
			 SVC_TYPE.put("T", "Telemetry other than GIG Switched Networks");
			 SVC_TYPE.put("U", "SONET");
			 SVC_TYPE.put("V", "Voice other than GIG Switched Networks");
			 SVC_TYPE.put("W", "Defense Switched Network - Europe");
			 SVC_TYPE.put("X", "Package System. Channel accounting by DISA");
			 SVC_TYPE.put("Y", "Control Management Signaling D.C. or data other than GIG Switched Networks");
			 SVC_TYPE.put("Z", "Non-DSN Intersite Trunk Circuit");
			 SVC_TYPE.put("1", "NIPRNET Access Line");
			 SVC_TYPE.put("2", "DISN Inter-Nodal Circuit (INC)");
			 SVC_TYPE.put("3", "FTS Access Line");
			 SVC_TYPE.put("4", "FTS Interswitch Trunk");
			 SVC_TYPE.put("5", "Broadband Inter-Nodal Circuit");
			 SVC_TYPE.put("6", "Indirect NIPRNET/SIPRNET Access through a Concentrator (Note: This code will only be used to identify long-haul dedicated circuits which access a concentrator and will not be Used for Camp/Post/Station/Base circuits. Also this code will not be used to identify NIPRNET/SIPRNET resources.)");
			 SVC_TYPE.put("7", "Indirect DTH Access through an intermediate relay (automatic or manual)");
			 SVC_TYPE.put("8", "NIPRNET/SIPRNET Backbone");
			 SVC_TYPE.put("9", "SIPRNET Access Line");
			 SVC_TYPE.put("0", "Package System. Channel/Fabric/Slot/Port. Accounting by DISA.");
			 
			 String fullCCSD = "";
			 if (tso.get("Full CCSD").length() == 8) {fullCCSD = tso.get("Full CCSD");}
			 else {fullCCSD = tso.get("Alternate CCSD");}
			 tso.put("Requesting Department", DEPT_CODES.get(fullCCSD.substring(0, 1)));
			 tso.put("Circuit Use", USE_CODE.get(fullCCSD.substring(1, 2)));
			 tso.put("Type of Service", SVC_TYPE.get(fullCCSD.substring(3, 1)));

			 Collection collect = tso.values();
			 
			 Object[] array = collect.toArray();
			 
			 for (Object element : array){
				 System.out.println();
			 }
			 return tso;
			}
	}
